### ISSUE TITLE
Plugin refuses to load in placeholder API

### ISSUE THREAD

**Issue by i1470s** [Tanguygab/AdvancedBungee-PlaceholderAPI-Expansion#1]
After constant restarts and debugging this expansion will not load.

i have installed from the offical Ecloud website and manually installed into expansions folder and it continues to refuse to load

i have noticed that it is not adding itself to the config file.

Following is an error from my Paper MC server runing 1.20.2 fully updated plugins
[00:47:38 WARN]: [PlaceholderAPI] Cannot load expansion advancedbungee due to an unknown issue.

this error is from my waterfall bungee cord proxy server
[00:48:35 WARN]: Error loading plugin PlaceholderAPI
java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1013) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:287) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.20-548.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:c996222:548]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 13 more

**Comment by Tanguygab** [comment]
did you enable bungeecord in your spigot.yml? 

and for the second error, you have to use the expansion asa Bungee plugin, not PlaceholderAPI.

**Comment by i1470s** [comment]
Ah that fixed it thank you very much!
